---
- hosts: sonarqube
  vars:
    sonar_download_url: https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.7.2.zip
    sonar_version_directory: sonarqube-6.7.2
  roles:
    - role: python_mysql_modules
      become: yes
    - role: java_internal
      become: yes
    - role: ansible-role-sonar
      become: yes
      ansible_distribution_major_version: 6
      mysql_packages:
        - mysql57
        - mysql57-server
    - role: geerlingguy.nginx
      become: yes
      ansible_distribution_major_version: 6
      nginx_vhosts:
        - listen: "80"
          server_name: "sonarqube.fastfeedback.rocks.conf"
          state: "present"
          template: "{{ nginx_vhost_template }}"
          filename: "sonarqube.fastfeedback.rocks.conf"
          extra_parameters: |
            location / {
                proxy_pass http://127.0.0.1:9000;
            }

