---
- hosts: sonarqube
  become: yes
  vars:
    sonar_download_url: https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.7.2.zip
    sonar_version_directory: sonarqube-6.7.2
  roles:
    - role: common
    - role: geerlingguy.java
      java_packages:
        - java-1.8.0-openjdk
    - role: geerlingguy.mysql
    - role: geerlingguy.sonar

